export default {
  Mtoe: "Mtoe",
  Mbtu: "Mbtu",
  Mb_per_d: "Mb/d",
  Mtce: "Mtce",
  Tcf_gas: "Tcf gas",
  Bcm: "Bcm",
  TWh: "TWh",
  Gbl_per_yr: "Gbl/yr",
  TJ: "TJ",
  Mmbtu: "Mmbtu",
  EJ: "EJ",
  toe: "toe",
  KWh: "KWh",
};
